// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIr6qdMckI8w7L2fHxhdlEPUXdIQcOPds',
    appId: '1:1043317349485:web:dd40ba43bfa17655b93364',
    messagingSenderId: '1043317349485',
    projectId: 'petnest-app1',
    authDomain: 'petnest-app1.firebaseapp.com',
    storageBucket: 'petnest-app1.firebasestorage.app',
    measurementId: 'G-GGG5LL2PNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWL0IbADrMrFNYY_2sYxk30DVg-ISnX0',
    appId: '1:1043317349485:android:5cee7a4917da23c0b93364',
    messagingSenderId: '1043317349485',
    projectId: 'petnest-app1',
    storageBucket: 'petnest-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfamevMqC5wLhs7TdD08DXzXjoR29Zias',
    appId: '1:1043317349485:ios:c57e49a46a334549b93364',
    messagingSenderId: '1043317349485',
    projectId: 'petnest-app1',
    storageBucket: 'petnest-app1.firebasestorage.app',
    iosClientId: '1043317349485-hf4rkk4bcagea71s7cm4ceqsfq9nlrg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfamevMqC5wLhs7TdD08DXzXjoR29Zias',
    appId: '1:1043317349485:ios:c57e49a46a334549b93364',
    messagingSenderId: '1043317349485',
    projectId: 'petnest-app1',
    storageBucket: 'petnest-app1.firebasestorage.app',
    iosClientId: '1043317349485-hf4rkk4bcagea71s7cm4ceqsfq9nlrg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIr6qdMckI8w7L2fHxhdlEPUXdIQcOPds',
    appId: '1:1043317349485:web:7e9f8ba7f7664a75b93364',
    messagingSenderId: '1043317349485',
    projectId: 'petnest-app1',
    authDomain: 'petnest-app1.firebaseapp.com',
    storageBucket: 'petnest-app1.firebasestorage.app',
    measurementId: 'G-542EKLWPEL',
  );
}
